Swithc to debug logs

diff --git a/.github/workflows/test-main.yml b/.github/workflows/test-main.yml
--- a/.github/workflows/test-main.yml
+++ b/.github/workflows/test-main.yml
@@ -146,6 +146,29 @@ jobs:
           cat server.log
           exit 1
         fi
+              
+
+        
+    - name: Run nettest client WSS test
+      run: |
+        cd test-run
+        
+        echo "Running nettest client test with WSS and -save..."
+        echo "Client command: ./nettest -c 127.0.0.1 -save -ws -tls"
+        
+        GITHUB_SHA="${{ github.sha }}" \
+        sudo timeout 60s ./nettest -c 127.0.0.1 -save -tls -ws -log debug
+        CLIENT_EXIT_CODE=$?
+        
+        echo "Client test completed"
+        echo "Client exit code: $CLIENT_EXIT_CODE"
+        
+        if [ $CLIENT_EXIT_CODE -ne 0 ]; then
+          echo "❌ Client WSS test failed"
+          exit 1
+        fi
+        
+        echo "✅ Client WSS test completed successfully"
         
     - name: Run nettest client TCP test
       run: |
@@ -210,29 +233,7 @@ jobs:
         
         echo "✅ Client WSS test completed successfully"
 
-        
-
-        
-    - name: Run nettest client WSS test
-      run: |
-        cd test-run
-        
-        echo "Running nettest client test with WSS and -save..."
-        echo "Client command: ./nettest -c 127.0.0.1 -save -ws -tls"
-        
-        GITHUB_SHA="${{ github.sha }}" \
-        sudo timeout 60s ./nettest -c 127.0.0.1 -save -tls -ws -log info
-        CLIENT_EXIT_CODE=$?
-        
-        echo "Client test completed"
-        echo "Client exit code: $CLIENT_EXIT_CODE"
-        
-        if [ $CLIENT_EXIT_CODE -ne 0 ]; then
-          echo "❌ Client WSS test failed"
-          exit 1
-        fi
-        
-        echo "✅ Client WSS test completed successfully"
+  
         
     - name: Test completed
       run: |
